### ISSUE TITLE
Feature request: Edge side module filtering

### ISSUE THREAD

**Issue by sandervandevelde** [veyalla/logspout-loganalytics#2]
Hello, your project has potential. But currently it seems I have no control over the amount of logging messages sent to the cloud.

Is it possible to filter messages:
- By module name (only sent messages from certain modules- whitelist)
- By regex or another kind of format to accept (whitelist) or to ignore (blacklist)

**Comment by veyalla** [comment]
@sandervandevelde 

logspout has some filtering options like sending stdout vs only stderr and sending logs only from certain containers. See Q #2 from faq: https://github.com/veyalla/logspout-loganalytics/blob/master/faq.md
 
Q #3 has suggestions on using edge deployments to enable/disable logging easily.

**Comment by sandervandevelde** [comment]
Yes, the [FAQ](https://github.com/veyalla/logspout-loganalytics/blob/master/faq.md) gives more information, thanks.
But is it possible to combine filters? What if I want to filter both on StdErr (filter.sources=stderr) and a module (filter.labels=a:tempSensor*)?

**Comment by veyalla** [comment]
I believe something like this would work: 
```
"Cmd": [
        "loganalytics://?filter.name=temp*&filter.sources=stderr"
    ],
```

**Comment by sandervandevelde** [comment]
Thanks.
