### ISSUE TITLE
Log Module does not work properly when trying to deploy to kubernetes edge workload

### ISSUE THREAD

**Issue by El-Hassan** [veyalla/logspout-loganalytics#4]
I have an edge device that run minikube workload. when I tried to deploy log module as mentioned in read-me steps, the container got stuck in ContainerCreating phase and never ends.
Looking deeper, I found the following warning appears:

 Warning  FailedMount  17s (x7 over 49s)  kubelet, minikube  MountVolume.SetUp failed for volume "varrundockersock" : hostPath type check failed: /var/run/docker.sock is not a directory

**Comment by veyalla** [comment]
This solution will not work on Kubernetes as it relies on getting logs from the Docker socket. Consider using the solution here: https://github.com/Microsoft/OMS-docker/tree/master/Kubernetes
